spring:
  datasource:
    url: jdbc:mysql://google/restaurantdb?cloudSqlInstance=uni-final-project-422814:europe-central2:restaurant-app-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: root
    password: localadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    password: "jzek gemm dyyi lgpt"
    username: "hubert.kiszkavp@gmail.com"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "75e735f2ea1cc9cd1d1b"
            client-secret: "24b2e3cbee64776974c3bb8a7f31498beef1bae1"